spring:
  application:
    name: largefileupload

  servlet:
    multipart:
      enabled: false
  datasource:
    url: jdbc:postgresql://postgres:5432/root
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update

app:
  fileDir: target

